name: webview_checker
description: Android and iOS webview component testing application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.0+8

environment:
  sdk: ">=2.9.0 <3.0.0"
  flutter: 1.20.2

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.8
  flutter_launcher_icons: ^0.7.4
  url_launcher: ^5.2.5
  shared_preferences: ^0.5.4+5

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon/icon-foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
