name: webview_checker
description: Android and iOS webview component testing application.
publish_to: none
version: 2.0.0+13

environment:
  sdk: ">=2.13.0<3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  webview_flutter: ^2.0.10

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon/icon-foreground.png"

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
