name: webview_checker
description: Android and iOS webview component testing application.

version: 1.3.2+12

environment:
  sdk: ">=2.12.2<3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.2
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "icon/icon-foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  pedantic: any
  pedantic_mono: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
