# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :certificates do
    match(
      app_identifier: ["com.app.dr1009.webviewChecker"],
      type: "appstore",
      readonly: true)
    match(
      app_identifier: ["com.app.dr1009.webviewChecker.debug"],
      type: "development",
      readonly: true)
    match(
      app_identifier: ["com.app.dr1009.webviewChecker.adhoc"],
      type: "adhoc",
      readonly: true)
  end

  lane :adhoc do
    desc 'Build a new release for AdHob test'
    match(
      type: "adhoc",
      app_identifier: "com.app.dr1009.webviewChecker.adhoc")

    # build iOS app
    gym(
      scheme: "adhoc",
      configuration: "Adhoc",
      export_method: "ad-hoc"
    )
  end

  lane :prod do
    desc 'Build a new release'
        match(
          type: "appstore",
          app_identifier: "com.app.dr1009.webviewChecker")

        # build iOS app
        gym(
          scheme: "prod",
          configuration: "Release",
          export_method: "app-store"
        )

  end
end